name: Container Image

on:
  schedule:
    # every Wednesday morning
    - cron: 7 7 * * 3
  push:
    branches: [ main ]
    tags: [ ** ]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      platforms:
        description: "comma-separated list of platforms to build for, downstream supported are linux/amd64,linux/s390x,linux/ppc64le; note: clang is broken on s390x (RHEL-15874), also cross-builds take more than 6 hours so we don't do them"
        default: linux/amd64
      custom_tag:
        description: a custom tag on remote repo you want image to be tagged with
        default: scratch

jobs:
  call-build:
    uses: ./.github/workflows/container-image-buildah.yml
    with:
      platforms: ${{ inputs.platforms == '' && 'linux/amd64' || inputs.platforms }}
      custom_tag: ${{ inputs.custom_tag }}
